require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - lib/jekyll-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - vendor/**/*
Metrics/AbcSize:
  Max: 22
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 21
Metrics/PerceivedComplexity:
  Max: 9
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
Style/FrozenStringLiteralComment:
  Enabled: false
